option_blocks:
  - start: "09:30"
    end: "09:45" 
    name: "Market Open"
  - start: "12:00"
    end: "16:00"
    name: "Lunch Block"  
  - start: "18:00"
    end: "21:15"
    name: "Asian Open"
multipliers:
  /MES: 5
  MES: 5
  MES_OPT: 5
strategies:
  - 5AM
  - NORMAL
  - BULL-PUT
  - BEAR-CALL
  - BULL-PUT-OVERNIGHT
