option_blocks:
  - start: "09:30"
    end: "09:45" 
    name: "Market Open"
  - start: "12:00"
    end: "16:00"
    name: "Lunch Block"  
  - start: "18:00"
    end: "21:15"
    name: "Asian Open"
multipliers:
  /MES: 5
  MES: 5
  MES_OPT: 5
strategies:
  - 5AM
  - NORMAL
  - BULL-PUT
  - BEAR-CALL
  - BULL-PUT-OVERNIGHT
costs:
  FUTURE:
    commission_per_contract: "1.10"
    exchange_fees_per_contract: "0.37"
    regulatory_fees_per_contract: "0.00"
  OPTION:
    commission_per_contract: "1.25"
    exchange_fees_per_contract: "0.50"
    regulatory_fees_per_contract: "0.02"


# Trading System Configuration
# Customize all prompts and settings here
# Configurable Prompts - Customize these to match your trading style

prompt_triggers:
  on_entry: true   # Show prompts when opening trades (buying)
  on_exit: false  

prompts:
  # Core Market Analysis Prompts
  economic_events: "Any major economic events today? (Fed, CPI, NFP, etc.)"
  auction: "Treasury auction schedule affecting rates today?"
  earnings: "Major earnings releases this week that could impact market?"
  fed_speakers: "Fed speakers scheduled today? (Check Fed calendar)"
  market_conditions: "Current market conditions/sentiment? (Bullish/Bearish/Neutral)"
  volatility: "VIX level and volatility environment? (High/Normal/Low)"
  
